config/routes.rb
Rails.application.routes.draw do
  resources :p_users
  resources :accounts_activation, only: [:edit]

  get 'payment/filter' => 'payment#filter' #for form filtering based on selection
  get 'payment' => 'payment#new'
  get 'payment/:id' => 'payment#show'
  post 'payment' => 'payment#submit'

  get 'home' => 'home#show'

  get 'register' => 'p_users#new'
  get 'me/:id' => 'p_users#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/p_user.rb
class PUser < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}

  before_save :downcase_email
  before_create :create_activation_digest

  has_secure_password

  has_attached_file :avatar, styles: {medium: '300x300>', thumb: '100x100>'}, default_url: '/images/:style/missing.jpg'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_attached_file :id_slash_passport_pic, styles: {medium: '400x400>', thumb: '100x100>'}, default_url: '/images/:style/missing_id.jpg'
  validates_attachment_content_type :id_slash_passport_pic, content_type: /\Aimage\/.*\Z/


  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Returns a random token.
  def PUser.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns the hash digest of the given string.
  def PUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token = PUser.new_token
    self.activation_digest = PUser.digest(activation_token)
  end


end

app/controllers/p_users_controller.rb
class PUsersController < ApplicationController
  before_action :set_p_user, only: [:show, :edit, :update, :destroy]

  # GET /p_users
  # GET /p_users.json
  def index
    @p_users = PUser.all
  end

  # GET /p_users/1
  # GET /p_users/1.json
  def show

    #make sure user is unverified before checking docs
    if (!@p_user.verified)
      verify_id_docs
    end

  end

  # GET /p_users/new
  def new
    @p_user = PUser.new
  end

  # GET /p_users/1/edit
  def edit
  end

  # POST /p_users
  # POST /p_users.json
  def create
    @p_user = PUser.new(p_user_params)

    respond_to do |format|
      if @p_user.save
        #activation things
        UserMailer.account_activation(@p_user).deliver_now
        flash[:info] = 'Please check your email to activate your account.'
        #redirect_to '/index.html'

        log_in @p_user # go to root or some please activate page isntead of login

        format.html { redirect_to @p_user, notice: 'success' }
        format.json { render :show, status: :created, location: @p_user }
      else
        format.html { render :new }
        format.json { render json: @p_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /p_users/1
  # PATCH/PUT /p_users/1.json
  def update
    respond_to do |format|
      if @p_user.update(p_user_params)
        format.html { redirect_to @p_user, notice: 'successfully updated.' }
        format.json { render :show, status: :ok, location: @p_user }
      else
        format.html { render :edit }
        format.json { render json: @p_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /p_users/1
  # DELETE /p_users/1.json
  def destroy
    @p_user.destroy
    respond_to do |format|
      format.html { redirect_to p_users_url, notice: 'P user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_p_user
    @p_user = PUser.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def p_user_params
    params.require(:p_user).permit(:first_name, :last_name, :email, :id_number, :password, :password_confirmation, :pic_url, :verified, :avatar, :id_slash_passport_pic)
  end
end

app/helpers/p_users_helper.rb
module PUsersHelper
end

app/views/p_users/_failed_verification_panel.html.erb
<!-- START panel-->
<div id="panelDemo10" class="panel panel-danger">
  <div class="panel-heading">Verification Failed</div>
  <div class="panel-body">
    <p>The Identification documents you uploaded did not match the details registered with this account. Contact customer service for assistance</p>
  </div>
  <div class="panel-footer">Click <a href="#"><%= link_to 'here', edit_p_user_path(@p_user) %></a> to re-submit documents</div>
</div>
<!-- END panel-->

app/views/p_users/_form.html.erb
<div class="row padded">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <!-- START panel-->
    <div class="panel panel-default">
      <div class="panel-heading">Profile Update</div>
      <div class="panel-body">

        <%= form_for(@p_user) do |f| %>
            <% if @p_user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@p_user.errors.count, "error") %> prohibited this p_user from being
                    saved:</h2>

                  <ul>
                    <% @p_user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="form-group has-feedback">
              <%= f.label :'Select profile picture', class: 'text-muted' %>
              <%= f.file_field :avatar %>
            </div>

            <% if !@p_user.verified %>
                <div class="form-group has-feedback">
                  <%= f.label :'Select verification documents (ID picture)', class: 'text-muted' %>
                  <%= f.file_field :id_slash_passport_pic %>
                </div>
            <% end %>

            <% if !@p_user.id_number %>
                <div class="form-group has-feedback">
                  <%= f.label :'ID/Passport Number', class: 'text-muted' %>
                  <%= f.text_field :id_number, class: 'form-control', placeholder: 'Enter ID/Passport number', id: 'editIdNumber' %>
                  <span class="fa fa-barcode form-control-feedback text-muted"></span>
                </div>
            <% end %>



            <%= f.submit 'Done', class: 'btn btn-block btn-primary mt-lg' %>

        <% end %>

      </div>
    </div>

    <!-- END panel-->
  </div>
  <div class="col-md-4"></div>
</div>

app/views/p_users/_incomplete_profile.html.erb
<!-- START panel-->
<div id="panelPortlet8" class="panel panel-danger">
  <div class="panel-heading portlet-handler">Complete your profile</div>
  <div class="panel-body">
    <p>Please provide your ID/Passport number and your phone number to facilitate verification. You could also change your profile pic while you are at it :)</p></div>
  <div class="panel-footer">Click <a href="#"><%= link_to 'here', edit_p_user_path(@p_user) %></a> update profile</div>
</div>
<!-- END panel-->

app/views/p_users/_unverified_panel.html.erb
<!-- START panel-->
<div id="panelDemo10" class="panel panel-warning">
  <div class="panel-heading">Verification Pending</div>
  <div class="panel-body">
    <p>Kindly upload photos of your identification documents. The names should at least match the ones
      used for subscription You'll be able to access a limited number of services in the mean
      time.</p>
  </div>
  <div class="panel-footer">Click <a href="#"><%= link_to 'here', edit_p_user_path(@p_user) %></a> to submit documents</div>
</div>
<!-- END panel-->

app/views/p_users/_verified_panel.html.erb
<div id="panelDemo9" class="panel panel-success">
  <div class="panel-heading">Verified
    <a href="#" data-tool="panel-dismiss" data-toggle="tooltip" title="Close Panel" class="pull-right">
      <em class="fa fa-times"></em>
    </a>
  </div>
  <div class="panel-body">
    <p>Your Identification documents were automatically verified, now you can access all services without
      restrictions</p>
  </div>
  <div class="panel-footer">:)</div>
</div>

app/views/p_users/edit.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'shared/head' %>

<body>

<div class="wrapper">
  <!-- Main section-->
  <%= render 'shared/frame' %>
  <section>
    <!-- Page content-->
    <div class="content-wrapper">
      <div class="unwrap">
        <%= render 'form' %>
      </div>
    </div>
  </section>
</div>
<%= render 'shared/footer' %>
<%= render 'shared/scripts' %>

</body>

</html>

<%= link_to 'Show', @p_user %> |
<%= link_to 'Back', p_users_path %>

app/views/p_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing P Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Id number</th>
      <th>Password</th>
      <th>Pic url</th>
      <th>Verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @p_users.each do |p_user| %>
      <tr>
        <td><%= p_user.first_name %></td>
        <td><%= p_user.last_name %></td>
        <td><%= p_user.email %></td>
        <td><%= p_user.id_number %></td>
        <td><%= p_user.password %></td>
        <td><%= p_user.verified %></td>
        <td><%= link_to 'Show', p_user %></td>
        <td><%= link_to 'Edit', edit_p_user_path(p_user) %></td>
        <td><%= link_to 'Destroy', p_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New P user', new_p_user_path %>

app/views/p_users/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= render 'shared/head' %>
</head>

<body>
<div class="wrapper">
  <div class="block-center">
    <div class="row padded">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <!-- START panel-->
        <div class="panel panel-dark panel-flat">
          <div class="panel-heading text-center">
            Bungoma County
          </div>
          <div class="panel-body">
            <p class="text-center pv">REGISTER TO ACCESS SERVICES</p>

            <%= form_for(@p_user) do |c| %>

                <%= render 'shared/error_messages' %>

                <div class="form-group has-feedback">

                  <%= c.label 'First name', class: 'text-muted' %>
                  <%= c.text_field :first_name, class: 'form-control', placeholder: 'Enter first name' %>
                  <span class="fa fa-user form-control-feedback text-muted"></span>
                </div>
                <div class="form-group has-feedback">
                  <%= c.label 'Last name', class: 'text-muted' %>
                  <%= c.text_field :last_name, class: 'form-control', placeholder: 'Enter last name' %>
                  <span class="fa fa-user-secret form-control-feedback text-muted"></span>
                </div>

                <div class="form-group has-feedback">
                  <%= c.label :'Email', class: 'text-muted' %>
                  <%= c.email_field :email, class: 'form-control', placeholder: 'Enter email' %>
                  <span class="fa fa-envelope form-control-feedback text-muted"></span>
                </div>

                <!--
            <div class="form-group has-feedback">
              <%= c.label :'ID/Passport number', class: 'text-muted' %>
              <%= c.text_field :id_number, class: 'form-control', placeholder: 'Enter ID/Passport number' %>
              <span class="fa fa-barcode form-control-feedback text-muted"></span>
            </div>
            -->

                <div class="form-group has-feedback">
                  <%= c.label :'Password', class: 'text-muted' %>
                  <%= c.password_field :password, class: 'form-control', placeholder: 'Enter password', type: 'password', id: 'signupInputPassword1' %>
                  <span class="fa fa-lock form-control-feedback text-muted"></span>
                </div>

                <div class="form-group has-feedback">
                  <%= c.label :'Re-type password', class: 'text-muted' %>
                  <%= c.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter password', type: 'password', id: 'signupInputPassword1' %>
                  <span class="fa fa-lock form-control-feedback text-muted"></span>
                </div>

                <div class="clearfix">
                  <div class="checkbox c-checkbox pull-left mt0">
                    <label>
                      <input type="checkbox" value="" required name="agreed">
                      <span class="fa fa-check"></span>I agree with the <a href="#">terms</a>
                    </label>
                  </div>
                </div>
                <%= c.submit 'Create my account', class: 'btn btn-block btn-primary mt-lg' %>


            <% end %>

            <p class="pt-lg text-center">Have an account?</p>
            <a href="login.html" class="btn btn-block btn-default">Sign in</a>
          </div>
        </div>
      </div>
      <div class="col-md-4"></div>

    </div>
    <!-- END panel-->
    <%= render 'shared/footer' %>

  </div>
</div>
<%= render 'shared/scripts' %>
</body>

</html>

app/views/p_users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'shared/head' %>

<body>
<div class="wrapper">
  <!-- Main section-->

  <%= render 'shared/frame' %>

  <section>
    <!-- Page content-->
    <div class="content-wrapper">
      <div class="unwrap">
        <div style="background-image: url(http://themicon.co/theme/angle/v3.2/backend-jquery/app/img/profile-bg.jpg)" class="bg-cover">
          <div class="p-xl text-center text-white">
            <%= image_tag @p_user.avatar.url(:medium), :class => 'img-thumbnail img-circle thumb128' %>
            <p></p>
            <h3 class="m0"><%= @p_user.first_name %> <%= @p_user.last_name %></h3>
            <p>Member since <%= @p_user.created_at %></p>
            <p><%= @p_user.email %></p>
          </div>
        </div>
        <div class="text-center bg-gray-dark p-lg mb-xl">
          <div class="row row-table">
            <div class="col-xs-4 br">
              <h3 class="m0">0</h3>
              <p class="m0">
                <span>Payments</span>
              </p>
            </div>
            <div class="col-xs-4 br">
              <h3 class="m0">0</h3>
              <p class="m0">Properties</p>
            </div>
            <div class="col-xs-4">
              <h3 class="m0">0</h3>
              <p class="m0">Requests</p>
            </div>
          </div>
        </div>
        <div class="p-lg">
          <div class="row">
            <div class="col-lg-4">

              <% if !@p_user.id_number %>
                  <%= render :partial => 'incomplete_profile' %>
              <% end %>

            </div>

            <div class="col-lg-4">
              <div class="panel panel-default">
                <div class="panel-body">
                  <div class="text-center">
                    <p id="notice"><%= notice %></p>

                    <h3 class="mt0"><%= @p_user.first_name %> <%= @p_user.last_name %></h3>
                    <p>Joined 2002</p>
                  </div>
                  <hr>
                  <ul class="list-unstyled ph-xl">
                    <li>
                      <em class="fa fa-home fa-fw mr-lg"></em>Prime Place
                    </li>
                    <li>
                      <em class="fa fa-briefcase fa-fw mr-lg"></em><a href="#">Town</a>
                    </li>
                    <li>
                      <em class="fa fa-graduation-cap fa-fw mr-lg"></em>Business
                    </li>
                  </ul>
                </div>
              </div>

            </div>
            <div class="col-lg-4">

              <% if @p_user.verified %>
                  <%= render :partial => 'verified_panel' %>
              <% end %>
              <% if !@p_user.verified && (@p_user.id_slash_passport_pic.url(:medium).include? 'missing_id') %>
                  <%= render :partial => 'unverified_panel' %>
              <% end %>
              <% if !@verified && !@p_user.verified && !(@p_user.id_slash_passport_pic.url(:medium).include? 'missing_id')  %>
                  <%= render :partial => 'failed_verification_panel' %>
              <% end %>


            </div>
          </div>
        </div>


      </div>
    </div>
  </section>
  <!-- Page footer-->
  <%= render 'shared/footer' %>
</div>

<%= render 'shared/scripts' %>

</body>

</html>