config/routes.rb
Rails.application.routes.draw do
  resources :p_users
  resources :accounts_activation, only: [:edit]

  get 'payment/filter' => 'payment#filter' #for form filtering based on selection
  get 'payment' => 'payment#new'
  get 'payment/:id' => 'payment#show'
  post 'payment' => 'payment#submit'

  get 'home' => 'home#show'

  get 'register' => 'p_users#new'
  get 'me/:id' => 'p_users#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<html lang="en">

<head>
  <link rel="stylesheet" href="/assets/bootstrap.css" id="bscss">
</head>
<body>

<% if @p_user.errors.any? %>

    <div role="alert" class="alert alert-danger">
      The form contains <%= pluralize(@p_user.errors.count, "error") %>.

    </div>
    <div id="error_explanation">

      <ul>
        <% @p_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

<% end %>
<script src="/assets/bootstrap.js"></script>
</body>


</html>

app/views/shared/_footer.html.erb
<div class="p-lg text-center">
  <span>&copy;</span>
  <span>2016</span>
  <span>-</span>
  <span>SGL</span>
  <br>
  <span>County of Bungoma Portal</span>
</div>

app/views/shared/_frame.html.erb
<!-- top navbar-->
<header class="topnavbar-wrapper">
  <!-- START Top Navbar-->
  <nav role="navigation" class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
      <a href="#/" class="navbar-brand">
        <!--<div class="brand-logo">
          <img src="img/logo.png" alt="App Logo" class="img-responsive">
        </div>
        <div class="brand-logo-collapsed">
          <img src="img/logo-single.png" alt="App Logo" class="img-responsive">
        </div>
        -->
      </a>
    </div>
    <!-- END navbar header-->
    <!-- START Nav wrapper-->
    <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
        <li>
          <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
          <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
            <em class="fa fa-navicon"></em>
          </a>
          <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
          <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
            <em class="fa fa-navicon"></em>
          </a>
        </li>

        <!-- START lock screen-->
        <li class=" ">
          <%= link_to logout_path, method: :delete do %>
              <em class="fa fa-lock "></em>
          <% end %>
        </li>
        <!-- END lock screen-->
      </ul>
      <!-- END Left navbar-->
    </div>
    <!-- END Nav wrapper-->

  </nav>
  <!-- END Top Navbar-->
</header>
<!-- sidebar-->
<aside class="aside">
  <!-- START Sidebar (left)-->
  <div class="aside-inner">
    <nav data-sidebar-anyclick-close="" class="sidebar">
      <!-- START sidebar nav-->
      <ul class="nav">
        <!-- Iterates over all sidebar items-->
        <li class="nav-heading ">
          <span data-localize="sidebar.heading.HEADER">Content</span>
        </li>

        <li class=" ">
          <a href="/home" title="Home">
            <em class="fa fa-home "></em>
            <span data-localize="sidebar.nav.HOME">Home</span>
          </a>
        </li>

        <li class=" ">
          <%= link_to id: session[:user_id], controller: 'p_users', action: 'show', id: session[:user_id] do %>
              <em class="fa fa-user "></em>
              <span data-localize="sidebar.nav.HOME">Profile</span>
          <% end %>
        </li>

      </ul>
      <!-- END sidebar nav-->
    </nav>
  </div>
  <!-- END Sidebar (left)-->
</aside>

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="bungoma county frederick n">
  <meta name="keywords" content="">
  <title>Profile</title>

  <!-- =============== VENDOR STYLES ===============-->
  <!-- FONT AWESOME -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

</head>

app/views/shared/_scripts.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>