config/routes.rb
Rails.application.routes.draw do
  resources :p_users
  resources :accounts_activation, only: [:edit]

  get 'payment/filter' => 'payment#filter' #for form filtering based on selection
  get 'payment' => 'payment#new'
  get 'payment/:id' => 'payment#show'
  post 'payment' => 'payment#submit'

  get 'home' => 'home#show'

  get 'register' => 'p_users#new'
  get 'me/:id' => 'p_users#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  def new
    list_wards
    list_revenue_subgroups
    list_payment_modes
  end

  def submit
    payment = Google::Apis::PaymentApiV1::Payment.new
    revenue = Google::Apis::RevenueApiV1::Revenue.new
    payment_mode = Google::Apis::PaymentModeApiV1::PaymentMode.new

    revenue.update!(id: params[:revenue])
    payment_mode.update!(id: params[:payment][:payment_mode_id])

    payment.update!(
        amount: params[:amount],
        p_user_id: session[:user_id],
        id: -1,
        narration: params[:narration],
        revenue: revenue,
        receipt_number: '#'+ SecureRandom.random_number(36 ** 10).to_s(36).upcase,
        transaction_date: Time.now.getutc.to_datetime,
        payment_mode: payment_mode)

    insert_payment(payment)
    get_payment payment.receipt_number #get the db auto genned number

    redirect_to action: 'show', id: @payment_result.receipt_number


  end

  def show
    get_payment params[:id]
  end


  def filter

    @revenues = list_revenues params[:sub_id], params[:ward_id]
    respond_to do |format|
      format.html { render json: @revenues }
    end

  end


end

app/helpers/payment_helper.rb
module PaymentHelper

  def list_wards
    @WardsApi = Google::Apis::WardsApiV1 #alias wards api
    @wards_api = @WardsApi::WardsApiService.new
    @wards = @wards_api.list.items
  end

  def list_revenue_subgroups
    @RevenueSubgroupApi = Google::Apis::RevenueSubgroupApiV1 #alias revenuesubgroups api
    @revenue_subgroup_api = @RevenueSubgroupApi::RevenueSubgroupApiService.new #init service

    @revenue_subgroups = @revenue_subgroup_api.list.items
  end

  def list_payment_modes
    @PaymentModeApi = Google::Apis::PaymentModeApiV1 #alias payment mode api
    @payment_mode_api = @PaymentModeApi::PaymentModeApiService.new #init service

    @payment_modes = @payment_mode_api.list.items
  end

  def list_revenues(sub_id, ward_id)
    @RevenueApi = Google::Apis::RevenueApiV1 # alias revenues api
    @revenue_api = @RevenueApi::RevenueApiService.new #init service

    @revenues = @revenue_api.list(revenue_sub_group_id: sub_id, sub_county_group_id: ward_id)
  end

  def insert_payment(payment)
    @PaymentApi = Google::Apis::PaymentApiV1 #alias payment api
    @payment_api = @PaymentApi::PaymentApiService.new
    @payment_api.insert(payment);
  end

  def get_payment(receipt_number)
    @PaymentApi = Google::Apis::PaymentApiV1 #alias payment api
    @payment_api = @PaymentApi::PaymentApiService.new
    @payment_result = @payment_api.validate_receipt(receipt_number)

  end


end

app/views/payment/_form.html.erb
<div class="row padded">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <!-- START panel-->
    <div class="panel panel-default">
      <div class="panel-heading">Make a payment</div>
      <div class="panel-body">

        <%= form_for(:payment, url: payment_path) do |f| %>

            <fieldset class="last-child">
              <div class="form-group">
                <label class="col-sm-2 control-label">Select</label>
                <div class="col-sm-10">
                  <select name="account" class="form-control m-b">
                    <option>Option 1</option>
                    <option>Option 2</option>
                    <option>Option 3</option>
                    <option>Option 4</option>
                  </select>
                  <br>
                  <div class="row">
                    <div class="col-lg-4">
                      <select multiple="" class="form-control">
                        <option>Option 1</option>
                        <option>Option 2</option>
                        <option>Option 3</option>
                        <option>Option 4</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
            </fieldset>

            <div class="form-group has-feedback">
              <%= f.label :'ID/Passport Number', class: 'text-muted' %>
              <%= f.text_field :id_number, class: 'form-control', placeholder: 'Enter ID/Passport number', id: 'editIdNumber' %>
              <span class="fa fa-barcode form-control-feedback text-muted"></span>
            </div>



            <%= f.submit 'Done', class: 'btn btn-block btn-primary mt-lg' %>

        <% end %>

      </div>
    </div>

    <!-- END panel-->
  </div>
  <div class="col-md-4"></div>
</div>

app/views/payment/_form_wizard.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Make a payment</div>
  <div class="panel-body">
    <%= form_for(:payment, url: payment_path, :html => {:id => 'example-form'}) do |f| %>
        <div>
          <h4>Basics
            <br>
            <small>Rudimentary payment details</small>
          </h4>
          <fieldset class="last-child">
            <div class="form-group">
              <label class="control-label">Service Category</label>
              <div>
                <%= f.select :revenue_subgroup_id, @revenue_subgroups.collect { |p| [p.name, p.id] }.insert(0, 'Select a category..'), {}, {class: 'form-control m-b required'} %>
              </div>
            </div>
            <br>
            <div class="form-group">
              <label class="control-label">Location</label>
              <div>
                <%= f.select :ward_id, @wards.collect { |p| [p.ward_name, p.county_code] }.insert(0, 'Select a location..'), {}, {class: 'form-control m-b required'} %>
              </div>
            </div>

            <br>
            <input style="display: none" id="amount" name="amount" type="text" class="form-control required">

            <div class="form-group">
              <label class="control-label">Service</label>
              <select id="service_options" name="revenue" class="form-control m-b required">
                <option value="0">Select..</option>
              </select>
            </div>

          </fieldset>
          <h4>Details
            <br>
            <small>Refine payment</small>
          </h4>
          <fieldset>
            <label for="narration">Narration *</label>
            <input id="narration" name="narration" type="text" class="form-control required" placeholder="Number plate, blobk number, etc">
            <br>

            <div class="row">
              <div class="col-md-4"></div>
              <div class="col-md-4">
                <!-- START widget-->
                <div class="panel widget">
                  <div class="panel-body bg-success text-center">
                    <div id="cost" class="text-lg m0">KSh. 3,000</div>
                    <p>Cost</p>
                    <div class="mb-lg"></div>
                    <em class="fa fa-credit-card text-alpha"></em>
                  </div>
                </div>
              </div>
              <div class="col-md-4"></div>
              <!-- END widget-->
            </div>
          </fieldset>


          <h4>Payment mode
            <br>
            <small>Preferred payment option</small>
          </h4>
          <fieldset>
            <div class="form-group">
              <% @payment_modes.each do |payment_mode| %>
                  <div class="radio">
                    <label>
                      <%= f.radio_button :payment_mode_id, payment_mode.id %>
                      <%= label :payment_mode, payment_mode.name %>
                    </label>
                  </div>

              <% end %>
            </div>
          </fieldset>
          <h4>Finish
            <br>
            <small>You are done now</small>
          </h4>
          <fieldset>
            <p class="lead">Depending on the payment mode selected, additional instructions or whatnot will appear
              here</p>

          </fieldset>
        </div>
    <% end %>
  </div>

</div>

app/views/payment/_receipt.html.erb
<div class="panel">
  <div class="panel-body">
    <button type="button" class="pull-right btn btn-default btn-sm">Copy this receipt</button>
    <h3 class="mt0"><%= @payment_result.receipt_number %></h3>
    <hr>
    <div class="row mb-lg">
      <div class="col-lg-4 col-xs-6 br pv">
        <div class="row">
          <div class="col-md-2 text-center visible-md visible-lg">
            <em class="fa fa-barcode fa-4x text-muted"></em>
          </div>
          <div class="col-md-2 text-center visible-md visible-lg">
            <em class="fa fa-barcode fa-4x text-muted"></em>
          </div>
          <div class="col-md-10">
            <h4><%= @payment_result.narration %></h4>
            <address></address>
            <%= @payment_result.revenue.revenue_stream.name %>
            <br><%= @payment_result.revenue.revenue_units.name %>
            <br>Location
          </div>
        </div>
      </div>
      <div class="clearfix hidden-md hidden-lg">
        <hr>
      </div>
      <div class="col-lg-4 col-xs-6 br pv"></div>
      <div class="clearfix hidden-md hidden-lg">
        <hr>
      </div>
      <div class="col-lg-4 col-xs-6 pv">
        <div class="clearfix">
          <p class="pull-left">Receipt No.
          <p class="pull-right mr"><%= @payment_result.receipt_number %></p>
        </div>
        <div class="clearfix">
          <p class="pull-left">Date</p>
          <p class="pull-right mr"><%= @payment_result.transaction_date.to_datetime %></p>
        </div>

      </div>
    </div>
    <div class="table-responsive table-bordered mb-lg">
      <table class="table">
        <thead>
        <tr>
          <th>Item #</th>
          <th>Description</th>
          <th>Quantity</th>
          <th>Unit Price</th>
          <th class="text-right">Total</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= (@payment_result.id) %></td>
          <td><%= (@payment_result.revenue.revenue_subgroup.name) + ': '+
                      (@payment_result.narration) + ' - '+
                      (@payment_result.revenue.revenue_stream.name) +', '+
                      (@payment_result.revenue.revenue_units.name) %></td>
          <td>1</td>
          <td>KSh. <%= @payment_result.amount %></td>
          <td class="text-right">KSh. <%= @payment_result.amount %></td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-sm-offset-8 col-sm-4 pv">
        <div class="clearfix">
          <p class="pull-left">Subtotal</p>
          <p class="pull-right mr">KSh. <%= @payment_result.amount %></p>
        </div>
        <div class="clearfix">
          <p class="pull-left">Tax (0%)</p>
          <p class="pull-right mr">KSh. 0</p>
        </div>
        <div class="clearfix">
          <p class="pull-left h3">GRAND TOTAL</p>
          <p class="pull-right mr h3">KSh. <%= @payment_result.amount %></p>
        </div>
      </div>
    </div>
    <hr class="hidden-print">
    <div class="clearfix">
      <button type="button" onclick="window.print();" class="btn btn-default pull-left">Print</button>
      <button type="button" class="btn btn-success pull-right">Send Receipt</button>
    </div>
  </div>
</div>

app/views/payment/new.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'shared/head' %>

<body>

<div class="wrapper">
  <!-- Main section-->
  <%= render 'shared/frame' %>
  <section>
    <!-- Page content-->
    <div class="content-wrapper">
      <h3>Payment</h3>
      <%= render :partial => 'form_wizard' %>
    </div>
  </section>
</div>
<%= render 'shared/footer' %>
<%= render 'shared/scripts' %>
<%= javascript_include_tag 'payment.f', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/payment/show.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'shared/head' %>

<body>

<div class="wrapper">
  <!-- Main section-->
  <%= render 'shared/frame' %>
  <section>
    <!-- Page content-->
    <div class="content-wrapper">
      <h3>Receipt</h3>
      <%= render :partial => 'receipt' %>
    </div>
  </section>
</div>
<%= render 'shared/footer' %>
<%= render 'shared/scripts' %>

</body>

</html>